[[ITK]]
arch = "aarch64"
git-tree-sha1 = "793103372036b95e0162aa1f8f062c9e108fa8de"
os = "macos"

    [[ITK.download]]
    sha256 = "a6f781e9bc989e2ca22cb1045914347d5d5ea18140de5c5290d512c70a06004c"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.aarch64-apple-darwin.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9856816d847a86f64da2165e95de05ccd2bb72ef"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "2a354528773f18e3c88d69124b909706b66975a2423b21b6da6243a9c04561af"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.aarch64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6067bd2f6a8dee78daa1e48fce0ecb38dbef6962"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "f92aa67a1dd47a3d88e1f07612986ca7930708d997b95d0b990985b0f76d41f1"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e067e0ae1aa794b50924b12fd932c5d03210ae84"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "3f5afa504bdf6412f25a18439a02f782fd5adbdcf9ca1ad68c704e4addbee78f"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.aarch64-linux-musl-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f53c4ca6bb7ea0259625793cbdbd063cc722cb5a"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "c555dbd5b5e496912c9fe77a5bc4e3bb9a01afb11444993b4838af65abadbdb5"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.aarch64-linux-musl-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ea8066287c18b3529d76ed289ec133a0a48ad17"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "302d09a5f7cf51d200fee194a045ef0cf499d684d466fc80ba1d7f71c930f3cd"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4dee41869ed45b5612a1b1c6551baa5d1369752"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "99325becc220443915fef0f6b8fde1ec337bc6a89d86f572c1189c4896d1a7f4"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a75132681f768945ef94ddbbb880ad4dd8a60a2"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "f99ed6c70aef7823b05b74e171e04873f74f775f0f544d3c2810b030fa535a67"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82ad77ef1c6aca8589f0e9e8277208e0c5e94f43"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "b0a072c31888d1fda87409a03848a6ed3df737058d48878e567dd95bf549a2e9"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ce3e05e51a3a1df86e35fd415c5ff00b6e58cd3"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "0331056f41c70c7bbe968fc6276d5d0ee4f3787b97afffc7da22c2d352740d79"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a7d29741f32e7e2d8df084a20c8c262e6fb5bf9"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "e73162326dc4237c629de647376a7cbb58d63f5234f872a6d730e1cc309d74a2"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f959454115ab520e1f23e04991af2c67c8cd216"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "5f88edcb9dcb1ea90667c7732c9bfe4c278ce0f87f6d814864a74683b5904092"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "722e7b82c656fc785d1901b5f53500933038e23a"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "b2ee516d8a3c6ca8005b704e6788c901d87030958ea74a2f3aa6005d37d8c329"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f6a1ac287ffb3779b17893665c0e24025918a7a"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "eb39b65b487d8adbcb550c83150018a9bdc674ea1d66db18ae450e897badb0f0"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "258a66d13b5eaa52308d550bf63a94629c7c2001"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "0f4682e2eaa72c31181a7de4a3f4f704a14284e549b0f32577f2c5b438be1ecd"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
git-tree-sha1 = "a2438ed7743fc76b9120eb1cd694fd268fd00f46"
os = "macos"

    [[ITK.download]]
    sha256 = "47eb7e41ebd8b96ed098424818d87f822f09afc0675514a4f386b2451aad50f9"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.x86_64-apple-darwin.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84def33c6d46a61596f3917b1ba2840515c2a706"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "8fb31eb4c30f29130458daeb2251f54bcecd26938aff4aa205a2089746b0e43f"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.x86_64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41642a1e334042c0a832960be6f06a7a3b6c229c"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "24ac5b22d6c51494fde47c1a78a6badf53c758a03bf74bd7ae78faae155de3fe"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b77435f35431dbc9e26617c48a8942b53a469c0"
os = "windows"

    [[ITK.download]]
    sha256 = "32501e31c5f14fa15a474bfd2b7a2d35da4a0aadad625d85ba2e90fb8c432439"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddab88e21c18c1384882b6276125fe14ecc21408"
os = "windows"

    [[ITK.download]]
    sha256 = "67df166103d0ca91537318454ceac81c29bd86947ef64df1e820ff311a3f3514"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.3+0/ITK.v5.3.3.x86_64-w64-mingw32-cxx11.tar.gz"
