[[ITK]]
arch = "aarch64"
git-tree-sha1 = "f88af286ec32d32aff0fad922cd99f740a6e9935"
os = "macos"

    [[ITK.download]]
    sha256 = "9b5db93fba590d3d04e0e625b1a16870a0498b432efee87ebd3cfea9330f101a"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.aarch64-apple-darwin.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac2c5bf466a374aeebb40d1e6188b275edad8d9b"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "e7756e3f0b1ad6ef09e65b462a2da0435bb2a19e8f06e139ad2c9b2e1ba09834"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ddca956c2e17e89cccbdfda4d665584861b5a5c"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "ede3adc7bb3c6c26e1d2a5c3c930a2d3ed5df1f51c68d313fb2f5511e736d29c"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e1fb7c35196aada7597c2dd776b0bb4728fdc36"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "005d8195e3c366cb3319095fa0d8c93d163e8d81bbc5cb17a848af2a34b8c533"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7f8243f89c28ac551adec08402e5a9d5719959a"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "43b7f301e307fc06f7af20b6edc1aa139cb3219527f256f8713bf47c8b29982c"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70349730b62d1b91800d9ccc1b1619ca9dadfd54"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "d95b1b3740396631c0cbeaf4ab92d7df4f31cc42aa77120d9bf140526fb6ec6a"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eac4c64a2d36e7bbc02c5c478b4b56a209d5e96"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "3c6a63112c74d6a086783d60b1af96884aeeaa209b7723afe3fe7cf53c72b38f"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81ed2a1f1a55971f75e1ad3d758475cff1ba44e5"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "4a45bd655a218eef4f87594f4f40b69af7cfcbaf725882bac711c308b80ae265"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c418d1f0f4444013ae8d53f03c9d14797d63851c"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "af32f6a150053f0ec7109e15c05fe74a9e5e3ede5500f9c02df219b6b6cd5653"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7ca03cfd690b3d53afa28901f23b943a2a6256e"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "5893a2bd52c35b8637397fd791c9b6ee914af9eda5bdc4dd5b0eab5f222172c0"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "520d6ec01a707817340e8d622355e8c36995b921"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "790c9410ef161744c65ef09749b7876eea1b9b470e694d63be26fe7d828307eb"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0407f1068d9b373ad485795a9d2d3927a356832"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "6530f424fdc3f9285c1e3fb7651ffadf781adf8bc8d229c355ec7e758660eb16"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62556d543634ba134b0c44ad8076507c4dfffcbc"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "768fcdde5713ce6788fd1fcc3c2d0ba35b14e161c8138916e1416195693c0de8"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90a3368ba3eabc168130615284f73bc4f46f839a"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "8c8b4ed58744065261cda88a13cf15f11bf01c7130533b480d191c5bdb85f823"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1959cb0aa530abd3a2ff2104c9721b10db10421"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "d11fba9d4d6d265eed7a1ca4a41da625f5204b0a316903062e674aa084cb4572"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
git-tree-sha1 = "a6b9ba1c85a0e7e9c152c8d1e60db57b579a5b03"
os = "macos"

    [[ITK.download]]
    sha256 = "6b1af4a1fdee388d7bee5c5f599325290a36e508edcff12c6402955da1bcbf3e"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.x86_64-apple-darwin.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "422d7756f75781fc25cc4021353a0f061fcba8b0"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "a68795f19be5a3b2f40ec54d307de2f9ac76cd46fe0a32e80ccca7801c8b7d20"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e06cd65d970dd397f702127e07a3c6d205ddd47"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "50a4c766b63b49dd898c1e25c8fefe094d26255fb213194a8da30fcc6ad526ed"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e254040d64a6cdb08ff32b50ce2ef0746142def1"
os = "windows"

    [[ITK.download]]
    sha256 = "d97df836c5d0b58436b3341d9ce58c786bbef41effdcf6aaa8b71939c6e429e3"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae6c800defc6a317c268c812af6f306a94ba985d"
os = "windows"

    [[ITK.download]]
    sha256 = "50c3bae9284c8acfdfa98b9f497fda58c55af39a0304aac20903d9cb22d4196d"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.1+2/ITK.v5.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
