[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "643790bd92da2ade8bd7380be74e5a6ffbcbd9a7"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "d62340c38edcba9dab1310028ba1ebd4cad048f490cebfd4b3958128e037887a"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4027eac5e404d77205bb87e4d642adbba0357865"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "bfbc90eb734060d48622faa5ddf57abcca269daf043e238d95ae49044e881525"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef863b0a45202f869a1f873bbd0cc29e68d8d094"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "eb1f3a17ccbc2189f4087ac52a10e91fffa9cfae11ff8f6c2d9d5f0ae603e438"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[ITK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fa7728a1e6fd2a0806be3c6cd5b3339949079bf"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "f28ef93004cef9ade078e5a237711c66de29a7ddca02808a7dc695f8d117ed7f"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a2f42a7433b318de08cacc4ca7c9da9821f4d2d"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "46d2416f77a42219829268ed4934779c4505b4a4f18d6f36de9313d27714360d"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9f53d7c44ac4eac577a4085b9ea2fad46feb16a"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "c8df1a084f21d0a30f8e08e040cd286a8bf5a00003613f8419fa086ae544aee6"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "227bb02937cd4f327fdcfcd42c844b34106d8dda"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "5a376b53f42eb69be4aab27a1e18e479fd5c13a5ce4580213b4b02d1beb173b5"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a84eed190e8b7b32f44825b08c2f985941f78e5c"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "6abbb64f03c31abedfb2bb4472e85f3fb3623888450f11ead21d4a95c9469a68"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c45179478bc112a8f4fb827991b4cf833b280c5"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "f91c2651d96c666ddd1fb307393cc1efc44467e40efce6612ad8cfbe321b16fd"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80de4559f5a7aac688d4f133b7c08f70b488d2da"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "1becca7ddd4d3ec22ba173aac83afff88249b914a1a98dcb2a165c545b0cdc83"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb7669b33dd2373b819c6ba7fa062e6b30b7e7bf"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "5e0a41e4ff59ff60d4c5b37ab00481888beeb0cd823e0103a27a5fdf45daebf2"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ITK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5fa14874c66df96ef0bf9f6376b20753b7fcc7f"
libc = "musl"
os = "linux"

    [[ITK.download]]
    sha256 = "41915525e3b3788d588d8bf445ed1822e0bd24431d58425ccf158348ae0d1437"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc64ccc411add6a8a8a570845fef92eb277de054"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "12bffbf73f29e7e5f9c101173009e4c9b5dcfd050117990868de41d85ef8c757"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94d21196b38478e384f75688a632e42224b9b57b"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "3375e34f047f6c70dbbfed01debfa888a9af6bd43b28ebfdcda57bd4303c6777"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0eff7ba1bcc684c2df351385ad960b36dc5cb14"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "1bad6c69f5a72ba608d9c5a8819485586bac27112776d12ee8e94cafdf80d6f7"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dea974ca390d826393e232290f6bb5eaf619ebd"
libc = "glibc"
os = "linux"

    [[ITK.download]]
    sha256 = "c28b13153f90de33458c39fb051bf270a5d9de4ace33f01e082d2df2e31071d0"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dcc3f2fb3e6cd316cdaf54bd24bbf63420f9227"
os = "windows"

    [[ITK.download]]
    sha256 = "fe3c688adecc8e86c123c7c5ae277a971533de016bb0bdf70b05aeb173d26e54"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ITK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86a24a3bd4d38e6cbac20ad0e86667ef8b8309f5"
os = "windows"

    [[ITK.download]]
    sha256 = "3ff413a0e9d7a3f57f718bdec0eaf90e4de55b455343caa0087429205e867d77"
    url = "https://github.com/JuliaBinaryWrappers/ITK_jll.jl/releases/download/ITK-v5.3.0+2/ITK.v5.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
