# Autogenerated wrapper script for ITK_jll for armv7l-linux-musleabihf-cxx03
export libITKBiasCorrection, libITKColormap, libITKCommon, libITKConvolution, libITKDICOMParser, libITKDeformableMesh, libITKDenoising, libITKDiffusionTensorImage, libITKFFT, libITKFastMarching, libITKIOBMP, libITKIOBioRad, libITKIOBruker, libITKIOCSV, libITKIOGDCM, libITKIOGE, libITKIOGIPL, libITKIOHDF5, libITKIOIPL, libITKIOImageBase, libITKIOJPEG, libITKIOJPEG2000, libITKIOLSM, libITKIOMINC, libITKIOMRC, libITKIOMeshBYU, libITKIOMeshBase, libITKIOMeshFreeSurfer, libITKIOMeshGifti, libITKIOMeshOBJ, libITKIOMeshOFF, libITKIOMeshVTK, libITKIOMeta, libITKIONIFTI, libITKIONRRD, libITKIOPNG, libITKIOSiemens, libITKIOSpatialObjects, libITKIOStimulate, libITKIOTIFF, libITKIOTransformBase, libITKIOTransformHDF5, libITKIOTransformInsightLegacy, libITKIOTransformMatlab, libITKIOVTK, libITKIOXML, libITKImageFeature, libITKImageIntensity, libITKKLMRegionGrowing, libITKLabelMap, libITKMarkovRandomFieldsClassifiers, libITKMathematicalMorphology, libITKMesh, libITKMetaIO, libITKNrrdIO, libITKOptimizers, libITKOptimizersv4, libITKPDEDeformableRegistration, libITKPath, libITKPolynomials, libITKQuadEdgeMesh, libITKQuadEdgeMeshFiltering, libITKRegionGrowing, libITKRegistrationMethodsv4, libITKSmoothing, libITKSpatialObjects, libITKStatistics, libITKTestKernel, libITKTransform, libITKTransformFactory, libITKVNLInstantiation, libITKVTK, libITKVideoCore, libITKVideoIO, libITKWatersheds, libITKgiftiio, libITKniftiio, libITKznz, libitkNetlibSlatec, libitkdoubleConversion, libitkgdcmCommon, libitkgdcmDICT, libitkgdcmDSED, libitkgdcmIOD, libitkgdcmMSFF, libitklbfgs, libitkminc2, libitkopenjpeg, libitksys, libitkv3p_netlib, libitkvcl, libitkvnl, libitkvnl_algo

using Expat_jll
using FFTW_jll
using HDF5_jll
using JpegTurbo_jll
using Libtiff_jll
using libpng_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ITK")
JLLWrappers.@declare_library_product(libITKBiasCorrection, "libITKBiasCorrection-5.3.so.1")
JLLWrappers.@declare_library_product(libITKColormap, "libITKColormap-5.3.so.1")
JLLWrappers.@declare_library_product(libITKCommon, "libITKCommon-5.3.so.1")
JLLWrappers.@declare_library_product(libITKConvolution, "libITKConvolution-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDICOMParser, "libITKDICOMParser-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDeformableMesh, "libITKDeformableMesh-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDenoising, "libITKDenoising-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDiffusionTensorImage, "libITKDiffusionTensorImage-5.3.so.1")
JLLWrappers.@declare_library_product(libITKFFT, "libITKFFT-5.3.so.1")
JLLWrappers.@declare_library_product(libITKFastMarching, "libITKFastMarching-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBMP, "libITKIOBMP-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBioRad, "libITKIOBioRad-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBruker, "libITKIOBruker-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOCSV, "libITKIOCSV-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGDCM, "libITKIOGDCM-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGE, "libITKIOGE-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGIPL, "libITKIOGIPL-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOHDF5, "libITKIOHDF5-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOIPL, "libITKIOIPL-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOImageBase, "libITKIOImageBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOJPEG, "libITKIOJPEG-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOJPEG2000, "libITKIOJPEG2000-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOLSM, "libITKIOLSM-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMINC, "libITKIOMINC-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMRC, "libITKIOMRC-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshBYU, "libITKIOMeshBYU-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshBase, "libITKIOMeshBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshFreeSurfer, "libITKIOMeshFreeSurfer-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshGifti, "libITKIOMeshGifti-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshOBJ, "libITKIOMeshOBJ-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshOFF, "libITKIOMeshOFF-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshVTK, "libITKIOMeshVTK-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeta, "libITKIOMeta-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIONIFTI, "libITKIONIFTI-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIONRRD, "libITKIONRRD-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOPNG, "libITKIOPNG-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOSiemens, "libITKIOSiemens-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOSpatialObjects, "libITKIOSpatialObjects-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOStimulate, "libITKIOStimulate-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTIFF, "libITKIOTIFF-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformBase, "libITKIOTransformBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformHDF5, "libITKIOTransformHDF5-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformInsightLegacy, "libITKIOTransformInsightLegacy-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformMatlab, "libITKIOTransformMatlab-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOVTK, "libITKIOVTK-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOXML, "libITKIOXML-5.3.so.1")
JLLWrappers.@declare_library_product(libITKImageFeature, "libITKImageFeature-5.3.so.1")
JLLWrappers.@declare_library_product(libITKImageIntensity, "libITKImageIntensity-5.3.so.1")
JLLWrappers.@declare_library_product(libITKKLMRegionGrowing, "libITKKLMRegionGrowing-5.3.so.1")
JLLWrappers.@declare_library_product(libITKLabelMap, "libITKLabelMap-5.3.so.1")
JLLWrappers.@declare_library_product(libITKMarkovRandomFieldsClassifiers, "libITKMarkovRandomFieldsClassifiers-5.3.so.1")
JLLWrappers.@declare_library_product(libITKMathematicalMorphology, "libITKMathematicalMorphology-5.3.so.1")
JLLWrappers.@declare_library_product(libITKMesh, "libITKMesh-5.3.so.1")
JLLWrappers.@declare_library_product(libITKMetaIO, "libITKMetaIO-5.3.so.1")
JLLWrappers.@declare_library_product(libITKNrrdIO, "libITKNrrdIO-5.3.so.1")
JLLWrappers.@declare_library_product(libITKOptimizers, "libITKOptimizers-5.3.so.1")
JLLWrappers.@declare_library_product(libITKOptimizersv4, "libITKOptimizersv4-5.3.so.1")
JLLWrappers.@declare_library_product(libITKPDEDeformableRegistration, "libITKPDEDeformableRegistration-5.3.so.1")
JLLWrappers.@declare_library_product(libITKPath, "libITKPath-5.3.so.1")
JLLWrappers.@declare_library_product(libITKPolynomials, "libITKPolynomials-5.3.so.1")
JLLWrappers.@declare_library_product(libITKQuadEdgeMesh, "libITKQuadEdgeMesh-5.3.so.1")
JLLWrappers.@declare_library_product(libITKQuadEdgeMeshFiltering, "libITKQuadEdgeMeshFiltering-5.3.so.1")
JLLWrappers.@declare_library_product(libITKRegionGrowing, "libITKRegionGrowing-5.3.so.1")
JLLWrappers.@declare_library_product(libITKRegistrationMethodsv4, "libITKRegistrationMethodsv4-5.3.so.1")
JLLWrappers.@declare_library_product(libITKSmoothing, "libITKSmoothing-5.3.so.1")
JLLWrappers.@declare_library_product(libITKSpatialObjects, "libITKSpatialObjects-5.3.so.1")
JLLWrappers.@declare_library_product(libITKStatistics, "libITKStatistics-5.3.so.1")
JLLWrappers.@declare_library_product(libITKTestKernel, "libITKTestKernel-5.3.so.1")
JLLWrappers.@declare_library_product(libITKTransform, "libITKTransform-5.3.so.1")
JLLWrappers.@declare_library_product(libITKTransformFactory, "libITKTransformFactory-5.3.so.1")
JLLWrappers.@declare_library_product(libITKVNLInstantiation, "libITKVNLInstantiation-5.3.so.1")
JLLWrappers.@declare_library_product(libITKVTK, "libITKVTK-5.3.so.1")
JLLWrappers.@declare_library_product(libITKVideoCore, "libITKVideoCore-5.3.so.1")
JLLWrappers.@declare_library_product(libITKVideoIO, "libITKVideoIO-5.3.so.1")
JLLWrappers.@declare_library_product(libITKWatersheds, "libITKWatersheds-5.3.so.1")
JLLWrappers.@declare_library_product(libITKgiftiio, "libITKgiftiio-5.3.so.1")
JLLWrappers.@declare_library_product(libITKniftiio, "libITKniftiio-5.3.so.1")
JLLWrappers.@declare_library_product(libITKznz, "libITKznz-5.3.so.1")
JLLWrappers.@declare_library_product(libitkNetlibSlatec, "libitkNetlibSlatec-5.3.so.1")
JLLWrappers.@declare_library_product(libitkdoubleConversion, "libitkdouble-conversion-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmCommon, "libitkgdcmCommon-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmDICT, "libitkgdcmDICT-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmDSED, "libitkgdcmDSED-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmIOD, "libitkgdcmIOD-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmMSFF, "libitkgdcmMSFF-5.3.so.1")
JLLWrappers.@declare_library_product(libitklbfgs, "libitklbfgs-5.3.so.1")
JLLWrappers.@declare_library_product(libitkminc2, "libitkminc2-5.3.so.1")
JLLWrappers.@declare_library_product(libitkopenjpeg, "libitkopenjpeg-5.3.so.1")
JLLWrappers.@declare_library_product(libitksys, "libitksys-5.3.so.1")
JLLWrappers.@declare_library_product(libitkv3p_netlib, "libitkv3p_netlib-5.3.so.1")
JLLWrappers.@declare_library_product(libitkvcl, "libitkvcl-5.3.so.1")
JLLWrappers.@declare_library_product(libitkvnl, "libitkvnl-5.3.so.1")
JLLWrappers.@declare_library_product(libitkvnl_algo, "libitkvnl_algo-5.3.so.1")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, FFTW_jll, HDF5_jll, JpegTurbo_jll, Libtiff_jll, libpng_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libITKBiasCorrection,
        "lib/libITKBiasCorrection-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKColormap,
        "lib/libITKColormap-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKCommon,
        "lib/libITKCommon-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKConvolution,
        "lib/libITKConvolution-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDICOMParser,
        "lib/libITKDICOMParser-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDeformableMesh,
        "lib/libITKDeformableMesh-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDenoising,
        "lib/libITKDenoising-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDiffusionTensorImage,
        "lib/libITKDiffusionTensorImage-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFFT,
        "lib/libITKFFT-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFastMarching,
        "lib/libITKFastMarching-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBMP,
        "lib/libITKIOBMP-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBioRad,
        "lib/libITKIOBioRad-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBruker,
        "lib/libITKIOBruker-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOCSV,
        "lib/libITKIOCSV-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGDCM,
        "lib/libITKIOGDCM-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGE,
        "lib/libITKIOGE-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGIPL,
        "lib/libITKIOGIPL-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOHDF5,
        "lib/libITKIOHDF5-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOIPL,
        "lib/libITKIOIPL-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOImageBase,
        "lib/libITKIOImageBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG,
        "lib/libITKIOJPEG-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG2000,
        "lib/libITKIOJPEG2000-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOLSM,
        "lib/libITKIOLSM-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMINC,
        "lib/libITKIOMINC-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMRC,
        "lib/libITKIOMRC-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBYU,
        "lib/libITKIOMeshBYU-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBase,
        "lib/libITKIOMeshBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshFreeSurfer,
        "lib/libITKIOMeshFreeSurfer-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshGifti,
        "lib/libITKIOMeshGifti-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOBJ,
        "lib/libITKIOMeshOBJ-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOFF,
        "lib/libITKIOMeshOFF-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshVTK,
        "lib/libITKIOMeshVTK-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeta,
        "lib/libITKIOMeta-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONIFTI,
        "lib/libITKIONIFTI-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONRRD,
        "lib/libITKIONRRD-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOPNG,
        "lib/libITKIOPNG-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSiemens,
        "lib/libITKIOSiemens-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSpatialObjects,
        "lib/libITKIOSpatialObjects-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOStimulate,
        "lib/libITKIOStimulate-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTIFF,
        "lib/libITKIOTIFF-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformBase,
        "lib/libITKIOTransformBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformHDF5,
        "lib/libITKIOTransformHDF5-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformInsightLegacy,
        "lib/libITKIOTransformInsightLegacy-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformMatlab,
        "lib/libITKIOTransformMatlab-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOVTK,
        "lib/libITKIOVTK-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOXML,
        "lib/libITKIOXML-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageFeature,
        "lib/libITKImageFeature-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageIntensity,
        "lib/libITKImageIntensity-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKKLMRegionGrowing,
        "lib/libITKKLMRegionGrowing-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKLabelMap,
        "lib/libITKLabelMap-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMarkovRandomFieldsClassifiers,
        "lib/libITKMarkovRandomFieldsClassifiers-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMathematicalMorphology,
        "lib/libITKMathematicalMorphology-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMesh,
        "lib/libITKMesh-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMetaIO,
        "lib/libITKMetaIO-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKNrrdIO,
        "lib/libITKNrrdIO-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizers,
        "lib/libITKOptimizers-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizersv4,
        "lib/libITKOptimizersv4-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPDEDeformableRegistration,
        "lib/libITKPDEDeformableRegistration-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPath,
        "lib/libITKPath-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPolynomials,
        "lib/libITKPolynomials-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMesh,
        "lib/libITKQuadEdgeMesh-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMeshFiltering,
        "lib/libITKQuadEdgeMeshFiltering-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegionGrowing,
        "lib/libITKRegionGrowing-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegistrationMethodsv4,
        "lib/libITKRegistrationMethodsv4-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSmoothing,
        "lib/libITKSmoothing-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSpatialObjects,
        "lib/libITKSpatialObjects-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKStatistics,
        "lib/libITKStatistics-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTestKernel,
        "lib/libITKTestKernel-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransform,
        "lib/libITKTransform-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransformFactory,
        "lib/libITKTransformFactory-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVNLInstantiation,
        "lib/libITKVNLInstantiation-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVTK,
        "lib/libITKVTK-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoCore,
        "lib/libITKVideoCore-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoIO,
        "lib/libITKVideoIO-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKWatersheds,
        "lib/libITKWatersheds-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKgiftiio,
        "lib/libITKgiftiio-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKniftiio,
        "lib/libITKniftiio-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKznz,
        "lib/libITKznz-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkNetlibSlatec,
        "lib/libitkNetlibSlatec-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkdoubleConversion,
        "lib/libitkdouble-conversion-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmCommon,
        "lib/libitkgdcmCommon-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDICT,
        "lib/libitkgdcmDICT-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDSED,
        "lib/libitkgdcmDSED-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmIOD,
        "lib/libitkgdcmIOD-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmMSFF,
        "lib/libitkgdcmMSFF-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitklbfgs,
        "lib/libitklbfgs-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkminc2,
        "lib/libitkminc2-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkopenjpeg,
        "lib/libitkopenjpeg-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitksys,
        "lib/libitksys-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkv3p_netlib,
        "lib/libitkv3p_netlib-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvcl,
        "lib/libitkvcl-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl,
        "lib/libitkvnl-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl_algo,
        "lib/libitkvnl_algo-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
