# Autogenerated wrapper script for ITK_jll for x86_64-linux-gnu-cxx11
export libITKCommon, libITKConvolution, libITKDICOMParser, libITKDeformableMesh, libITKDenoising, libITKDiffusionTensorImage, libITKIOBMP, libITKIOBioRad, libITKIOBruker, libITKIOCSV, libITKIOGDCM, libITKIOGE, libITKIOGIPL, libITKIOHDF5, libITKIOIPL, libITKIOImageBase, libITKIOJPEG, libITKIOJPEG2000, libITKIOLSM, libITKIOMINC, libITKIOMRC, libITKIOMeshBYU, libITKIOMeshBase, libITKIOMeshFreeSurfer, libITKIOMeshGifti, libITKIOMeshOBJ, libITKIOMeshOFF, libITKIOMeshVTK, libITKIOMeta, libITKIONIFTI, libITKIONRRD, libITKIOPNG, libITKIOSpatialObjects, libITKIOStimulate, libITKIOTransformBase, libITKIOTransformHDF5, libITKImageFeature, libITKImageIntensity, libITKLabelMap, libITKMetaIO, libITKNrrdIO, libITKRegistrationMethodsv4, libITKSpatialObjects, libITKTestKernel, libITKTransform, libITKniftiio, libitkgdcmCommon, libitkgdcmDICT, libitkgdcmDSED, libitkgdcmIOD

using Expat_jll
using FFTW_jll
using HDF5_jll
using JpegTurbo_jll
using Libtiff_jll
using libpng_jll
using Eigen_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ITK")
JLLWrappers.@declare_library_product(libITKCommon, "libITKCommon-5.3.so.1")
JLLWrappers.@declare_library_product(libITKConvolution, "libITKConvolution-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDICOMParser, "libITKDICOMParser-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDeformableMesh, "libITKDeformableMesh-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDenoising, "libITKDenoising-5.3.so.1")
JLLWrappers.@declare_library_product(libITKDiffusionTensorImage, "libITKDiffusionTensorImage-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBMP, "libITKIOBMP-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBioRad, "libITKIOBioRad-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOBruker, "libITKIOBruker-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOCSV, "libITKIOCSV-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGDCM, "libITKIOGDCM-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGE, "libITKIOGE-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOGIPL, "libITKIOGIPL-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOHDF5, "libITKIOHDF5-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOIPL, "libITKIOIPL-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOImageBase, "libITKIOImageBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOJPEG, "libITKIOJPEG-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOJPEG2000, "libITKIOJPEG2000-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOLSM, "libITKIOLSM-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMINC, "libITKIOMINC-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMRC, "libITKIOMRC-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshBYU, "libITKIOMeshBYU-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshBase, "libITKIOMeshBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshFreeSurfer, "libITKIOMeshFreeSurfer-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshGifti, "libITKIOMeshGifti-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshOBJ, "libITKIOMeshOBJ-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshOFF, "libITKIOMeshOFF-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeshVTK, "libITKIOMeshVTK-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOMeta, "libITKIOMeta-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIONIFTI, "libITKIONIFTI-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIONRRD, "libITKIONRRD-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOPNG, "libITKIOPNG-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOSpatialObjects, "libITKIOSpatialObjects-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOStimulate, "libITKIOStimulate-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformBase, "libITKIOTransformBase-5.3.so.1")
JLLWrappers.@declare_library_product(libITKIOTransformHDF5, "libITKIOTransformHDF5-5.3.so.1")
JLLWrappers.@declare_library_product(libITKImageFeature, "libITKImageFeature-5.3.so.1")
JLLWrappers.@declare_library_product(libITKImageIntensity, "libITKImageIntensity-5.3.so.1")
JLLWrappers.@declare_library_product(libITKLabelMap, "libITKLabelMap-5.3.so.1")
JLLWrappers.@declare_library_product(libITKMetaIO, "libITKMetaIO-5.3.so.1")
JLLWrappers.@declare_library_product(libITKNrrdIO, "libITKNrrdIO-5.3.so.1")
JLLWrappers.@declare_library_product(libITKRegistrationMethodsv4, "libITKRegistrationMethodsv4-5.3.so.1")
JLLWrappers.@declare_library_product(libITKSpatialObjects, "libITKSpatialObjects-5.3.so.1")
JLLWrappers.@declare_library_product(libITKTestKernel, "libITKTestKernel-5.3.so.1")
JLLWrappers.@declare_library_product(libITKTransform, "libITKTransform-5.3.so.1")
JLLWrappers.@declare_library_product(libITKniftiio, "libITKniftiio-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmCommon, "libitkgdcmCommon-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmDICT, "libitkgdcmDICT-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmDSED, "libitkgdcmDSED-5.3.so.1")
JLLWrappers.@declare_library_product(libitkgdcmIOD, "libitkgdcmIOD-5.3.so.1")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, FFTW_jll, HDF5_jll, JpegTurbo_jll, Libtiff_jll, libpng_jll, Eigen_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libITKCommon,
        "lib/libITKCommon-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKConvolution,
        "lib/libITKConvolution-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDICOMParser,
        "lib/libITKDICOMParser-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDeformableMesh,
        "lib/libITKDeformableMesh-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDenoising,
        "lib/libITKDenoising-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDiffusionTensorImage,
        "lib/libITKDiffusionTensorImage-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBMP,
        "lib/libITKIOBMP-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBioRad,
        "lib/libITKIOBioRad-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBruker,
        "lib/libITKIOBruker-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOCSV,
        "lib/libITKIOCSV-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGDCM,
        "lib/libITKIOGDCM-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGE,
        "lib/libITKIOGE-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGIPL,
        "lib/libITKIOGIPL-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOHDF5,
        "lib/libITKIOHDF5-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOIPL,
        "lib/libITKIOIPL-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOImageBase,
        "lib/libITKIOImageBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG,
        "lib/libITKIOJPEG-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG2000,
        "lib/libITKIOJPEG2000-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOLSM,
        "lib/libITKIOLSM-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMINC,
        "lib/libITKIOMINC-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMRC,
        "lib/libITKIOMRC-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBYU,
        "lib/libITKIOMeshBYU-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBase,
        "lib/libITKIOMeshBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshFreeSurfer,
        "lib/libITKIOMeshFreeSurfer-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshGifti,
        "lib/libITKIOMeshGifti-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOBJ,
        "lib/libITKIOMeshOBJ-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOFF,
        "lib/libITKIOMeshOFF-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshVTK,
        "lib/libITKIOMeshVTK-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeta,
        "lib/libITKIOMeta-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONIFTI,
        "lib/libITKIONIFTI-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONRRD,
        "lib/libITKIONRRD-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOPNG,
        "lib/libITKIOPNG-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSpatialObjects,
        "lib/libITKIOSpatialObjects-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOStimulate,
        "lib/libITKIOStimulate-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformBase,
        "lib/libITKIOTransformBase-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformHDF5,
        "lib/libITKIOTransformHDF5-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageFeature,
        "lib/libITKImageFeature-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageIntensity,
        "lib/libITKImageIntensity-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKLabelMap,
        "lib/libITKLabelMap-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMetaIO,
        "lib/libITKMetaIO-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKNrrdIO,
        "lib/libITKNrrdIO-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegistrationMethodsv4,
        "lib/libITKRegistrationMethodsv4-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSpatialObjects,
        "lib/libITKSpatialObjects-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTestKernel,
        "lib/libITKTestKernel-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransform,
        "lib/libITKTransform-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKniftiio,
        "lib/libITKniftiio-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmCommon,
        "lib/libitkgdcmCommon-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDICT,
        "lib/libitkgdcmDICT-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDSED,
        "lib/libitkgdcmDSED-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmIOD,
        "lib/libitkgdcmIOD-5.3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
