# Autogenerated wrapper script for ITK_jll for x86_64-apple-darwin
export libITKBiasCorrection, libITKColormap, libITKCommon, libITKConvolution, libITKDICOMParser, libITKDeformableMesh, libITKDenoising, libITKDiffusionTensorImage, libITKFFT, libITKFastMarching, libITKIOBMP, libITKIOBioRad, libITKIOBruker, libITKIOCSV, libITKIOGDCM, libITKIOGE, libITKIOGIPL, libITKIOHDF5, libITKIOIPL, libITKIOImageBase, libITKIOJPEG, libITKIOJPEG2000, libITKIOLSM, libITKIOMINC, libITKIOMRC, libITKIOMeshBYU, libITKIOMeshBase, libITKIOMeshFreeSurfer, libITKIOMeshGifti, libITKIOMeshOBJ, libITKIOMeshOFF, libITKIOMeshVTK, libITKIOMeta, libITKIONIFTI, libITKIONRRD, libITKIOPNG, libITKIOSiemens, libITKIOSpatialObjects, libITKIOStimulate, libITKIOTIFF, libITKIOTransformBase, libITKIOTransformHDF5, libITKIOTransformInsightLegacy, libITKIOTransformMatlab, libITKIOVTK, libITKIOXML, libITKImageFeature, libITKImageIntensity, libITKKLMRegionGrowing, libITKLabelMap, libITKMarkovRandomFieldsClassifiers, libITKMathematicalMorphology, libITKMesh, libITKMetaIO, libITKNrrdIO, libITKOptimizers, libITKOptimizersv4, libITKPDEDeformableRegistration, libITKPath, libITKPolynomials, libITKQuadEdgeMesh, libITKQuadEdgeMeshFiltering, libITKRegionGrowing, libITKRegistrationMethodsv4, libITKSmoothing, libITKSpatialObjects, libITKStatistics, libITKTestKernel, libITKTransform, libITKTransformFactory, libITKVNLInstantiation, libITKVTK, libITKVideoCore, libITKVideoIO, libITKWatersheds, libITKgiftiio, libITKniftiio, libITKznz, libitkNetlibSlatec, libitkdoubleConversion, libitkgdcmCommon, libitkgdcmDICT, libitkgdcmDSED, libitkgdcmIOD, libitkgdcmMSFF, libitklbfgs, libitkminc2, libitkopenjpeg, libitksys, libitkv3p_netlib, libitkvcl, libitkvnl, libitkvnl_algo

using Expat_jll
using FFTW_jll
using HDF5_jll
using JpegTurbo_jll
using Libtiff_jll
using libpng_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ITK")
JLLWrappers.@declare_library_product(libITKBiasCorrection, "@rpath/libITKBiasCorrection-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKColormap, "@rpath/libITKColormap-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKCommon, "@rpath/libITKCommon-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKConvolution, "@rpath/libITKConvolution-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKDICOMParser, "@rpath/libITKDICOMParser-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKDeformableMesh, "@rpath/libITKDeformableMesh-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKDenoising, "@rpath/libITKDenoising-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKDiffusionTensorImage, "@rpath/libITKDiffusionTensorImage-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKFFT, "@rpath/libITKFFT-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKFastMarching, "@rpath/libITKFastMarching-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOBMP, "@rpath/libITKIOBMP-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOBioRad, "@rpath/libITKIOBioRad-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOBruker, "@rpath/libITKIOBruker-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOCSV, "@rpath/libITKIOCSV-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOGDCM, "@rpath/libITKIOGDCM-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOGE, "@rpath/libITKIOGE-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOGIPL, "@rpath/libITKIOGIPL-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOHDF5, "@rpath/libITKIOHDF5-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOIPL, "@rpath/libITKIOIPL-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOImageBase, "@rpath/libITKIOImageBase-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOJPEG, "@rpath/libITKIOJPEG-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOJPEG2000, "@rpath/libITKIOJPEG2000-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOLSM, "@rpath/libITKIOLSM-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMINC, "@rpath/libITKIOMINC-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMRC, "@rpath/libITKIOMRC-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshBYU, "@rpath/libITKIOMeshBYU-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshBase, "@rpath/libITKIOMeshBase-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshFreeSurfer, "@rpath/libITKIOMeshFreeSurfer-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshGifti, "@rpath/libITKIOMeshGifti-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshOBJ, "@rpath/libITKIOMeshOBJ-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshOFF, "@rpath/libITKIOMeshOFF-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeshVTK, "@rpath/libITKIOMeshVTK-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOMeta, "@rpath/libITKIOMeta-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIONIFTI, "@rpath/libITKIONIFTI-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIONRRD, "@rpath/libITKIONRRD-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOPNG, "@rpath/libITKIOPNG-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOSiemens, "@rpath/libITKIOSiemens-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOSpatialObjects, "@rpath/libITKIOSpatialObjects-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOStimulate, "@rpath/libITKIOStimulate-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOTIFF, "@rpath/libITKIOTIFF-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOTransformBase, "@rpath/libITKIOTransformBase-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOTransformHDF5, "@rpath/libITKIOTransformHDF5-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOTransformInsightLegacy, "@rpath/libITKIOTransformInsightLegacy-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOTransformMatlab, "@rpath/libITKIOTransformMatlab-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOVTK, "@rpath/libITKIOVTK-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKIOXML, "@rpath/libITKIOXML-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKImageFeature, "@rpath/libITKImageFeature-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKImageIntensity, "@rpath/libITKImageIntensity-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKKLMRegionGrowing, "@rpath/libITKKLMRegionGrowing-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKLabelMap, "@rpath/libITKLabelMap-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKMarkovRandomFieldsClassifiers, "@rpath/libITKMarkovRandomFieldsClassifiers-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKMathematicalMorphology, "@rpath/libITKMathematicalMorphology-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKMesh, "@rpath/libITKMesh-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKMetaIO, "@rpath/libITKMetaIO-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKNrrdIO, "@rpath/libITKNrrdIO-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKOptimizers, "@rpath/libITKOptimizers-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKOptimizersv4, "@rpath/libITKOptimizersv4-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKPDEDeformableRegistration, "@rpath/libITKPDEDeformableRegistration-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKPath, "@rpath/libITKPath-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKPolynomials, "@rpath/libITKPolynomials-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKQuadEdgeMesh, "@rpath/libITKQuadEdgeMesh-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKQuadEdgeMeshFiltering, "@rpath/libITKQuadEdgeMeshFiltering-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKRegionGrowing, "@rpath/libITKRegionGrowing-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKRegistrationMethodsv4, "@rpath/libITKRegistrationMethodsv4-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKSmoothing, "@rpath/libITKSmoothing-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKSpatialObjects, "@rpath/libITKSpatialObjects-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKStatistics, "@rpath/libITKStatistics-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKTestKernel, "@rpath/libITKTestKernel-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKTransform, "@rpath/libITKTransform-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKTransformFactory, "@rpath/libITKTransformFactory-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKVNLInstantiation, "@rpath/libITKVNLInstantiation-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKVTK, "@rpath/libITKVTK-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKVideoCore, "@rpath/libITKVideoCore-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKVideoIO, "@rpath/libITKVideoIO-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKWatersheds, "@rpath/libITKWatersheds-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKgiftiio, "@rpath/libITKgiftiio-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKniftiio, "@rpath/libITKniftiio-5.3.1.dylib")
JLLWrappers.@declare_library_product(libITKznz, "@rpath/libITKznz-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkNetlibSlatec, "@rpath/libitkNetlibSlatec-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkdoubleConversion, "@rpath/libitkdouble-conversion-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkgdcmCommon, "@rpath/libitkgdcmCommon-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkgdcmDICT, "@rpath/libitkgdcmDICT-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkgdcmDSED, "@rpath/libitkgdcmDSED-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkgdcmIOD, "@rpath/libitkgdcmIOD-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkgdcmMSFF, "@rpath/libitkgdcmMSFF-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitklbfgs, "@rpath/libitklbfgs-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkminc2, "@rpath/libitkminc2-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkopenjpeg, "@rpath/libitkopenjpeg-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitksys, "@rpath/libitksys-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkv3p_netlib, "@rpath/libitkv3p_netlib-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkvcl, "@rpath/libitkvcl-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkvnl, "@rpath/libitkvnl-5.3.1.dylib")
JLLWrappers.@declare_library_product(libitkvnl_algo, "@rpath/libitkvnl_algo-5.3.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, FFTW_jll, HDF5_jll, JpegTurbo_jll, Libtiff_jll, libpng_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libITKBiasCorrection,
        "lib/libITKBiasCorrection-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKColormap,
        "lib/libITKColormap-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKCommon,
        "lib/libITKCommon-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKConvolution,
        "lib/libITKConvolution-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDICOMParser,
        "lib/libITKDICOMParser-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDeformableMesh,
        "lib/libITKDeformableMesh-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDenoising,
        "lib/libITKDenoising-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDiffusionTensorImage,
        "lib/libITKDiffusionTensorImage-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFFT,
        "lib/libITKFFT-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFastMarching,
        "lib/libITKFastMarching-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBMP,
        "lib/libITKIOBMP-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBioRad,
        "lib/libITKIOBioRad-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBruker,
        "lib/libITKIOBruker-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOCSV,
        "lib/libITKIOCSV-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGDCM,
        "lib/libITKIOGDCM-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGE,
        "lib/libITKIOGE-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGIPL,
        "lib/libITKIOGIPL-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOHDF5,
        "lib/libITKIOHDF5-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOIPL,
        "lib/libITKIOIPL-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOImageBase,
        "lib/libITKIOImageBase-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG,
        "lib/libITKIOJPEG-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG2000,
        "lib/libITKIOJPEG2000-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOLSM,
        "lib/libITKIOLSM-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMINC,
        "lib/libITKIOMINC-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMRC,
        "lib/libITKIOMRC-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBYU,
        "lib/libITKIOMeshBYU-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBase,
        "lib/libITKIOMeshBase-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshFreeSurfer,
        "lib/libITKIOMeshFreeSurfer-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshGifti,
        "lib/libITKIOMeshGifti-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOBJ,
        "lib/libITKIOMeshOBJ-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOFF,
        "lib/libITKIOMeshOFF-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshVTK,
        "lib/libITKIOMeshVTK-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeta,
        "lib/libITKIOMeta-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONIFTI,
        "lib/libITKIONIFTI-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONRRD,
        "lib/libITKIONRRD-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOPNG,
        "lib/libITKIOPNG-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSiemens,
        "lib/libITKIOSiemens-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSpatialObjects,
        "lib/libITKIOSpatialObjects-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOStimulate,
        "lib/libITKIOStimulate-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTIFF,
        "lib/libITKIOTIFF-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformBase,
        "lib/libITKIOTransformBase-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformHDF5,
        "lib/libITKIOTransformHDF5-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformInsightLegacy,
        "lib/libITKIOTransformInsightLegacy-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformMatlab,
        "lib/libITKIOTransformMatlab-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOVTK,
        "lib/libITKIOVTK-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOXML,
        "lib/libITKIOXML-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageFeature,
        "lib/libITKImageFeature-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageIntensity,
        "lib/libITKImageIntensity-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKKLMRegionGrowing,
        "lib/libITKKLMRegionGrowing-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKLabelMap,
        "lib/libITKLabelMap-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMarkovRandomFieldsClassifiers,
        "lib/libITKMarkovRandomFieldsClassifiers-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMathematicalMorphology,
        "lib/libITKMathematicalMorphology-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMesh,
        "lib/libITKMesh-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMetaIO,
        "lib/libITKMetaIO-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKNrrdIO,
        "lib/libITKNrrdIO-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizers,
        "lib/libITKOptimizers-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizersv4,
        "lib/libITKOptimizersv4-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPDEDeformableRegistration,
        "lib/libITKPDEDeformableRegistration-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPath,
        "lib/libITKPath-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPolynomials,
        "lib/libITKPolynomials-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMesh,
        "lib/libITKQuadEdgeMesh-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMeshFiltering,
        "lib/libITKQuadEdgeMeshFiltering-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegionGrowing,
        "lib/libITKRegionGrowing-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegistrationMethodsv4,
        "lib/libITKRegistrationMethodsv4-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSmoothing,
        "lib/libITKSmoothing-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSpatialObjects,
        "lib/libITKSpatialObjects-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKStatistics,
        "lib/libITKStatistics-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTestKernel,
        "lib/libITKTestKernel-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransform,
        "lib/libITKTransform-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransformFactory,
        "lib/libITKTransformFactory-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVNLInstantiation,
        "lib/libITKVNLInstantiation-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVTK,
        "lib/libITKVTK-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoCore,
        "lib/libITKVideoCore-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoIO,
        "lib/libITKVideoIO-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKWatersheds,
        "lib/libITKWatersheds-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKgiftiio,
        "lib/libITKgiftiio-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKniftiio,
        "lib/libITKniftiio-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKznz,
        "lib/libITKznz-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkNetlibSlatec,
        "lib/libitkNetlibSlatec-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkdoubleConversion,
        "lib/libitkdouble-conversion-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmCommon,
        "lib/libitkgdcmCommon-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDICT,
        "lib/libitkgdcmDICT-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDSED,
        "lib/libitkgdcmDSED-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmIOD,
        "lib/libitkgdcmIOD-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmMSFF,
        "lib/libitkgdcmMSFF-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitklbfgs,
        "lib/libitklbfgs-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkminc2,
        "lib/libitkminc2-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkopenjpeg,
        "lib/libitkopenjpeg-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitksys,
        "lib/libitksys-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkv3p_netlib,
        "lib/libitkv3p_netlib-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvcl,
        "lib/libitkvcl-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl,
        "lib/libitkvnl-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl_algo,
        "lib/libitkvnl_algo-5.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
