# Autogenerated wrapper script for ITK_jll for x86_64-w64-mingw32-cxx03
export libITKBiasCorrection, libITKColormap, libITKCommon, libITKConvolution, libITKDICOMParser, libITKDeformableMesh, libITKDenoising, libITKDiffusionTensorImage, libITKFFT, libITKFastMarching, libITKIOBMP, libITKIOBioRad, libITKIOBruker, libITKIOCSV, libITKIOGDCM, libITKIOGE, libITKIOGIPL, libITKIOHDF5, libITKIOIPL, libITKIOImageBase, libITKIOJPEG, libITKIOJPEG2000, libITKIOLSM, libITKIOMINC, libITKIOMRC, libITKIOMeshBYU, libITKIOMeshBase, libITKIOMeshFreeSurfer, libITKIOMeshGifti, libITKIOMeshOBJ, libITKIOMeshOFF, libITKIOMeshVTK, libITKIOMeta, libITKIONIFTI, libITKIONRRD, libITKIOPNG, libITKIOSiemens, libITKIOSpatialObjects, libITKIOStimulate, libITKIOTIFF, libITKIOTransformBase, libITKIOTransformHDF5, libITKIOTransformInsightLegacy, libITKIOTransformMatlab, libITKIOVTK, libITKIOXML, libITKImageFeature, libITKImageIntensity, libITKKLMRegionGrowing, libITKLabelMap, libITKMarkovRandomFieldsClassifiers, libITKMathematicalMorphology, libITKMesh, libITKMetaIO, libITKNrrdIO, libITKOptimizers, libITKOptimizersv4, libITKPDEDeformableRegistration, libITKPath, libITKPolynomials, libITKQuadEdgeMesh, libITKQuadEdgeMeshFiltering, libITKRegionGrowing, libITKRegistrationMethodsv4, libITKSmoothing, libITKSpatialObjects, libITKStatistics, libITKTestKernel, libITKTransform, libITKTransformFactory, libITKVNLInstantiation, libITKVTK, libITKVideoCore, libITKVideoIO, libITKWatersheds, libITKgiftiio, libITKniftiio, libITKznz, libitkNetlibSlatec, libitkdoubleConversion, libitkgdcmCommon, libitkgdcmDICT, libitkgdcmDSED, libitkgdcmIOD, libitkgdcmMSFF, libitklbfgs, libitkminc2, libitkopenjpeg, libitksys, libitkv3p_netlib, libitkvcl, libitkvnl, libitkvnl_algo

using Expat_jll
using FFTW_jll
using HDF5_jll
using JpegTurbo_jll
using Libtiff_jll
using libpng_jll
using Eigen_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ITK")
JLLWrappers.@declare_library_product(libITKBiasCorrection, "libITKBiasCorrection-5.3.dll")
JLLWrappers.@declare_library_product(libITKColormap, "libITKColormap-5.3.dll")
JLLWrappers.@declare_library_product(libITKCommon, "libITKCommon-5.3.dll")
JLLWrappers.@declare_library_product(libITKConvolution, "libITKConvolution-5.3.dll")
JLLWrappers.@declare_library_product(libITKDICOMParser, "libITKDICOMParser-5.3.dll")
JLLWrappers.@declare_library_product(libITKDeformableMesh, "libITKDeformableMesh-5.3.dll")
JLLWrappers.@declare_library_product(libITKDenoising, "libITKDenoising-5.3.dll")
JLLWrappers.@declare_library_product(libITKDiffusionTensorImage, "libITKDiffusionTensorImage-5.3.dll")
JLLWrappers.@declare_library_product(libITKFFT, "libITKFFT-5.3.dll")
JLLWrappers.@declare_library_product(libITKFastMarching, "libITKFastMarching-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBMP, "libITKIOBMP-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBioRad, "libITKIOBioRad-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBruker, "libITKIOBruker-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOCSV, "libITKIOCSV-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGDCM, "libITKIOGDCM-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGE, "libITKIOGE-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGIPL, "libITKIOGIPL-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOHDF5, "libITKIOHDF5-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOIPL, "libITKIOIPL-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOImageBase, "libITKIOImageBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOJPEG, "libITKIOJPEG-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOJPEG2000, "libITKIOJPEG2000-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOLSM, "libITKIOLSM-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMINC, "libITKIOMINC-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMRC, "libITKIOMRC-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshBYU, "libITKIOMeshBYU-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshBase, "libITKIOMeshBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshFreeSurfer, "libITKIOMeshFreeSurfer-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshGifti, "libITKIOMeshGifti-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshOBJ, "libITKIOMeshOBJ-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshOFF, "libITKIOMeshOFF-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshVTK, "libITKIOMeshVTK-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeta, "libITKIOMeta-5.3.dll")
JLLWrappers.@declare_library_product(libITKIONIFTI, "libITKIONIFTI-5.3.dll")
JLLWrappers.@declare_library_product(libITKIONRRD, "libITKIONRRD-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOPNG, "libITKIOPNG-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOSiemens, "libITKIOSiemens-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOSpatialObjects, "libITKIOSpatialObjects-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOStimulate, "libITKIOStimulate-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTIFF, "libITKIOTIFF-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformBase, "libITKIOTransformBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformHDF5, "libITKIOTransformHDF5-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformInsightLegacy, "libITKIOTransformInsightLegacy-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformMatlab, "libITKIOTransformMatlab-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOVTK, "libITKIOVTK-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOXML, "libITKIOXML-5.3.dll")
JLLWrappers.@declare_library_product(libITKImageFeature, "libITKImageFeature-5.3.dll")
JLLWrappers.@declare_library_product(libITKImageIntensity, "libITKImageIntensity-5.3.dll")
JLLWrappers.@declare_library_product(libITKKLMRegionGrowing, "libITKKLMRegionGrowing-5.3.dll")
JLLWrappers.@declare_library_product(libITKLabelMap, "libITKLabelMap-5.3.dll")
JLLWrappers.@declare_library_product(libITKMarkovRandomFieldsClassifiers, "libITKMarkovRandomFieldsClassifiers-5.3.dll")
JLLWrappers.@declare_library_product(libITKMathematicalMorphology, "libITKMathematicalMorphology-5.3.dll")
JLLWrappers.@declare_library_product(libITKMesh, "libITKMesh-5.3.dll")
JLLWrappers.@declare_library_product(libITKMetaIO, "libITKMetaIO-5.3.dll")
JLLWrappers.@declare_library_product(libITKNrrdIO, "libITKNrrdIO-5.3.dll")
JLLWrappers.@declare_library_product(libITKOptimizers, "libITKOptimizers-5.3.dll")
JLLWrappers.@declare_library_product(libITKOptimizersv4, "libITKOptimizersv4-5.3.dll")
JLLWrappers.@declare_library_product(libITKPDEDeformableRegistration, "libITKPDEDeformableRegistration-5.3.dll")
JLLWrappers.@declare_library_product(libITKPath, "libITKPath-5.3.dll")
JLLWrappers.@declare_library_product(libITKPolynomials, "libITKPolynomials-5.3.dll")
JLLWrappers.@declare_library_product(libITKQuadEdgeMesh, "libITKQuadEdgeMesh-5.3.dll")
JLLWrappers.@declare_library_product(libITKQuadEdgeMeshFiltering, "libITKQuadEdgeMeshFiltering-5.3.dll")
JLLWrappers.@declare_library_product(libITKRegionGrowing, "libITKRegionGrowing-5.3.dll")
JLLWrappers.@declare_library_product(libITKRegistrationMethodsv4, "libITKRegistrationMethodsv4-5.3.dll")
JLLWrappers.@declare_library_product(libITKSmoothing, "libITKSmoothing-5.3.dll")
JLLWrappers.@declare_library_product(libITKSpatialObjects, "libITKSpatialObjects-5.3.dll")
JLLWrappers.@declare_library_product(libITKStatistics, "libITKStatistics-5.3.dll")
JLLWrappers.@declare_library_product(libITKTestKernel, "libITKTestKernel-5.3.dll")
JLLWrappers.@declare_library_product(libITKTransform, "libITKTransform-5.3.dll")
JLLWrappers.@declare_library_product(libITKTransformFactory, "libITKTransformFactory-5.3.dll")
JLLWrappers.@declare_library_product(libITKVNLInstantiation, "libITKVNLInstantiation-5.3.dll")
JLLWrappers.@declare_library_product(libITKVTK, "libITKVTK-5.3.dll")
JLLWrappers.@declare_library_product(libITKVideoCore, "libITKVideoCore-5.3.dll")
JLLWrappers.@declare_library_product(libITKVideoIO, "libITKVideoIO-5.3.dll")
JLLWrappers.@declare_library_product(libITKWatersheds, "libITKWatersheds-5.3.dll")
JLLWrappers.@declare_library_product(libITKgiftiio, "libITKgiftiio-5.3.dll")
JLLWrappers.@declare_library_product(libITKniftiio, "libITKniftiio-5.3.dll")
JLLWrappers.@declare_library_product(libITKznz, "libITKznz-5.3.dll")
JLLWrappers.@declare_library_product(libitkNetlibSlatec, "libitkNetlibSlatec-5.3.dll")
JLLWrappers.@declare_library_product(libitkdoubleConversion, "libitkdouble-conversion-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmCommon, "libitkgdcmCommon-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmDICT, "libitkgdcmDICT-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmDSED, "libitkgdcmDSED-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmIOD, "libitkgdcmIOD-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmMSFF, "libitkgdcmMSFF-5.3.dll")
JLLWrappers.@declare_library_product(libitklbfgs, "libitklbfgs-5.3.dll")
JLLWrappers.@declare_library_product(libitkminc2, "libitkminc2-5.3.dll")
JLLWrappers.@declare_library_product(libitkopenjpeg, "libitkopenjpeg-5.3.dll")
JLLWrappers.@declare_library_product(libitksys, "libitksys-5.3.dll")
JLLWrappers.@declare_library_product(libitkv3p_netlib, "libitkv3p_netlib-5.3.dll")
JLLWrappers.@declare_library_product(libitkvcl, "libitkvcl-5.3.dll")
JLLWrappers.@declare_library_product(libitkvnl, "libitkvnl-5.3.dll")
JLLWrappers.@declare_library_product(libitkvnl_algo, "libitkvnl_algo-5.3.dll")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, FFTW_jll, HDF5_jll, JpegTurbo_jll, Libtiff_jll, libpng_jll, Eigen_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libITKBiasCorrection,
        "bin\\libITKBiasCorrection-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKColormap,
        "bin\\libITKColormap-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKCommon,
        "bin\\libITKCommon-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKConvolution,
        "bin\\libITKConvolution-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDICOMParser,
        "bin\\libITKDICOMParser-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDeformableMesh,
        "bin\\libITKDeformableMesh-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDenoising,
        "bin\\libITKDenoising-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDiffusionTensorImage,
        "bin\\libITKDiffusionTensorImage-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFFT,
        "bin\\libITKFFT-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKFastMarching,
        "bin\\libITKFastMarching-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBMP,
        "bin\\libITKIOBMP-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBioRad,
        "bin\\libITKIOBioRad-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBruker,
        "bin\\libITKIOBruker-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOCSV,
        "bin\\libITKIOCSV-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGDCM,
        "bin\\libITKIOGDCM-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGE,
        "bin\\libITKIOGE-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGIPL,
        "bin\\libITKIOGIPL-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOHDF5,
        "bin\\libITKIOHDF5-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOIPL,
        "bin\\libITKIOIPL-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOImageBase,
        "bin\\libITKIOImageBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG,
        "bin\\libITKIOJPEG-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG2000,
        "bin\\libITKIOJPEG2000-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOLSM,
        "bin\\libITKIOLSM-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMINC,
        "bin\\libITKIOMINC-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMRC,
        "bin\\libITKIOMRC-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBYU,
        "bin\\libITKIOMeshBYU-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBase,
        "bin\\libITKIOMeshBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshFreeSurfer,
        "bin\\libITKIOMeshFreeSurfer-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshGifti,
        "bin\\libITKIOMeshGifti-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOBJ,
        "bin\\libITKIOMeshOBJ-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOFF,
        "bin\\libITKIOMeshOFF-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshVTK,
        "bin\\libITKIOMeshVTK-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeta,
        "bin\\libITKIOMeta-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONIFTI,
        "bin\\libITKIONIFTI-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONRRD,
        "bin\\libITKIONRRD-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOPNG,
        "bin\\libITKIOPNG-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSiemens,
        "bin\\libITKIOSiemens-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSpatialObjects,
        "bin\\libITKIOSpatialObjects-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOStimulate,
        "bin\\libITKIOStimulate-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTIFF,
        "bin\\libITKIOTIFF-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformBase,
        "bin\\libITKIOTransformBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformHDF5,
        "bin\\libITKIOTransformHDF5-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformInsightLegacy,
        "bin\\libITKIOTransformInsightLegacy-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformMatlab,
        "bin\\libITKIOTransformMatlab-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOVTK,
        "bin\\libITKIOVTK-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOXML,
        "bin\\libITKIOXML-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageFeature,
        "bin\\libITKImageFeature-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageIntensity,
        "bin\\libITKImageIntensity-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKKLMRegionGrowing,
        "bin\\libITKKLMRegionGrowing-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKLabelMap,
        "bin\\libITKLabelMap-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMarkovRandomFieldsClassifiers,
        "bin\\libITKMarkovRandomFieldsClassifiers-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMathematicalMorphology,
        "bin\\libITKMathematicalMorphology-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMesh,
        "bin\\libITKMesh-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMetaIO,
        "bin\\libITKMetaIO-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKNrrdIO,
        "bin\\libITKNrrdIO-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizers,
        "bin\\libITKOptimizers-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKOptimizersv4,
        "bin\\libITKOptimizersv4-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPDEDeformableRegistration,
        "bin\\libITKPDEDeformableRegistration-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPath,
        "bin\\libITKPath-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKPolynomials,
        "bin\\libITKPolynomials-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMesh,
        "bin\\libITKQuadEdgeMesh-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKQuadEdgeMeshFiltering,
        "bin\\libITKQuadEdgeMeshFiltering-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegionGrowing,
        "bin\\libITKRegionGrowing-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegistrationMethodsv4,
        "bin\\libITKRegistrationMethodsv4-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSmoothing,
        "bin\\libITKSmoothing-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSpatialObjects,
        "bin\\libITKSpatialObjects-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKStatistics,
        "bin\\libITKStatistics-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTestKernel,
        "bin\\libITKTestKernel-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransform,
        "bin\\libITKTransform-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransformFactory,
        "bin\\libITKTransformFactory-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVNLInstantiation,
        "bin\\libITKVNLInstantiation-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVTK,
        "bin\\libITKVTK-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoCore,
        "bin\\libITKVideoCore-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKVideoIO,
        "bin\\libITKVideoIO-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKWatersheds,
        "bin\\libITKWatersheds-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKgiftiio,
        "bin\\libITKgiftiio-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKniftiio,
        "bin\\libITKniftiio-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKznz,
        "bin\\libITKznz-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkNetlibSlatec,
        "bin\\libitkNetlibSlatec-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkdoubleConversion,
        "bin\\libitkdouble-conversion-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmCommon,
        "bin\\libitkgdcmCommon-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDICT,
        "bin\\libitkgdcmDICT-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDSED,
        "bin\\libitkgdcmDSED-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmIOD,
        "bin\\libitkgdcmIOD-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmMSFF,
        "bin\\libitkgdcmMSFF-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitklbfgs,
        "bin\\libitklbfgs-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkminc2,
        "bin\\libitkminc2-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkopenjpeg,
        "bin\\libitkopenjpeg-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitksys,
        "bin\\libitksys-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkv3p_netlib,
        "bin\\libitkv3p_netlib-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvcl,
        "bin\\libitkvcl-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl,
        "bin\\libitkvnl-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkvnl_algo,
        "bin\\libitkvnl_algo-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
