# Autogenerated wrapper script for ITK_jll for x86_64-w64-mingw32-cxx11
export libITKCommon, libITKConvolution, libITKDICOMParser, libITKDeformableMesh, libITKDenoising, libITKDiffusionTensorImage, libITKIOBMP, libITKIOBioRad, libITKIOBruker, libITKIOCSV, libITKIOGDCM, libITKIOGE, libITKIOGIPL, libITKIOHDF5, libITKIOIPL, libITKIOImageBase, libITKIOJPEG, libITKIOJPEG2000, libITKIOLSM, libITKIOMINC, libITKIOMRC, libITKIOMeshBYU, libITKIOMeshBase, libITKIOMeshFreeSurfer, libITKIOMeshGifti, libITKIOMeshOBJ, libITKIOMeshOFF, libITKIOMeshVTK, libITKIOMeta, libITKIONIFTI, libITKIONRRD, libITKIOPNG, libITKIOSpatialObjects, libITKIOStimulate, libITKIOTransformBase, libITKIOTransformHDF5, libITKImageFeature, libITKImageIntensity, libITKLabelMap, libITKMetaIO, libITKNrrdIO, libITKRegistrationMethodsv4, libITKSpatialObjects, libITKTestKernel, libITKTransform, libITKniftiio, libitkgdcmCommon, libitkgdcmDICT, libitkgdcmDSED, libitkgdcmIOD

using Expat_jll
using FFTW_jll
using HDF5_jll
using JpegTurbo_jll
using Libtiff_jll
using libpng_jll
using Eigen_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ITK")
JLLWrappers.@declare_library_product(libITKCommon, "libITKCommon-5.3.dll")
JLLWrappers.@declare_library_product(libITKConvolution, "libITKConvolution-5.3.dll")
JLLWrappers.@declare_library_product(libITKDICOMParser, "libITKDICOMParser-5.3.dll")
JLLWrappers.@declare_library_product(libITKDeformableMesh, "libITKDeformableMesh-5.3.dll")
JLLWrappers.@declare_library_product(libITKDenoising, "libITKDenoising-5.3.dll")
JLLWrappers.@declare_library_product(libITKDiffusionTensorImage, "libITKDiffusionTensorImage-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBMP, "libITKIOBMP-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBioRad, "libITKIOBioRad-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOBruker, "libITKIOBruker-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOCSV, "libITKIOCSV-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGDCM, "libITKIOGDCM-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGE, "libITKIOGE-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOGIPL, "libITKIOGIPL-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOHDF5, "libITKIOHDF5-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOIPL, "libITKIOIPL-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOImageBase, "libITKIOImageBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOJPEG, "libITKIOJPEG-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOJPEG2000, "libITKIOJPEG2000-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOLSM, "libITKIOLSM-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMINC, "libITKIOMINC-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMRC, "libITKIOMRC-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshBYU, "libITKIOMeshBYU-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshBase, "libITKIOMeshBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshFreeSurfer, "libITKIOMeshFreeSurfer-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshGifti, "libITKIOMeshGifti-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshOBJ, "libITKIOMeshOBJ-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshOFF, "libITKIOMeshOFF-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeshVTK, "libITKIOMeshVTK-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOMeta, "libITKIOMeta-5.3.dll")
JLLWrappers.@declare_library_product(libITKIONIFTI, "libITKIONIFTI-5.3.dll")
JLLWrappers.@declare_library_product(libITKIONRRD, "libITKIONRRD-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOPNG, "libITKIOPNG-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOSpatialObjects, "libITKIOSpatialObjects-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOStimulate, "libITKIOStimulate-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformBase, "libITKIOTransformBase-5.3.dll")
JLLWrappers.@declare_library_product(libITKIOTransformHDF5, "libITKIOTransformHDF5-5.3.dll")
JLLWrappers.@declare_library_product(libITKImageFeature, "libITKImageFeature-5.3.dll")
JLLWrappers.@declare_library_product(libITKImageIntensity, "libITKImageIntensity-5.3.dll")
JLLWrappers.@declare_library_product(libITKLabelMap, "libITKLabelMap-5.3.dll")
JLLWrappers.@declare_library_product(libITKMetaIO, "libITKMetaIO-5.3.dll")
JLLWrappers.@declare_library_product(libITKNrrdIO, "libITKNrrdIO-5.3.dll")
JLLWrappers.@declare_library_product(libITKRegistrationMethodsv4, "libITKRegistrationMethodsv4-5.3.dll")
JLLWrappers.@declare_library_product(libITKSpatialObjects, "libITKSpatialObjects-5.3.dll")
JLLWrappers.@declare_library_product(libITKTestKernel, "libITKTestKernel-5.3.dll")
JLLWrappers.@declare_library_product(libITKTransform, "libITKTransform-5.3.dll")
JLLWrappers.@declare_library_product(libITKniftiio, "libITKniftiio-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmCommon, "libitkgdcmCommon-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmDICT, "libitkgdcmDICT-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmDSED, "libitkgdcmDSED-5.3.dll")
JLLWrappers.@declare_library_product(libitkgdcmIOD, "libitkgdcmIOD-5.3.dll")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, FFTW_jll, HDF5_jll, JpegTurbo_jll, Libtiff_jll, libpng_jll, Eigen_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libITKCommon,
        "bin\\libITKCommon-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKConvolution,
        "bin\\libITKConvolution-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDICOMParser,
        "bin\\libITKDICOMParser-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDeformableMesh,
        "bin\\libITKDeformableMesh-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDenoising,
        "bin\\libITKDenoising-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKDiffusionTensorImage,
        "bin\\libITKDiffusionTensorImage-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBMP,
        "bin\\libITKIOBMP-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBioRad,
        "bin\\libITKIOBioRad-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOBruker,
        "bin\\libITKIOBruker-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOCSV,
        "bin\\libITKIOCSV-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGDCM,
        "bin\\libITKIOGDCM-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGE,
        "bin\\libITKIOGE-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOGIPL,
        "bin\\libITKIOGIPL-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOHDF5,
        "bin\\libITKIOHDF5-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOIPL,
        "bin\\libITKIOIPL-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOImageBase,
        "bin\\libITKIOImageBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG,
        "bin\\libITKIOJPEG-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOJPEG2000,
        "bin\\libITKIOJPEG2000-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOLSM,
        "bin\\libITKIOLSM-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMINC,
        "bin\\libITKIOMINC-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMRC,
        "bin\\libITKIOMRC-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBYU,
        "bin\\libITKIOMeshBYU-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshBase,
        "bin\\libITKIOMeshBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshFreeSurfer,
        "bin\\libITKIOMeshFreeSurfer-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshGifti,
        "bin\\libITKIOMeshGifti-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOBJ,
        "bin\\libITKIOMeshOBJ-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshOFF,
        "bin\\libITKIOMeshOFF-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeshVTK,
        "bin\\libITKIOMeshVTK-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOMeta,
        "bin\\libITKIOMeta-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONIFTI,
        "bin\\libITKIONIFTI-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIONRRD,
        "bin\\libITKIONRRD-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOPNG,
        "bin\\libITKIOPNG-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOSpatialObjects,
        "bin\\libITKIOSpatialObjects-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOStimulate,
        "bin\\libITKIOStimulate-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformBase,
        "bin\\libITKIOTransformBase-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKIOTransformHDF5,
        "bin\\libITKIOTransformHDF5-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageFeature,
        "bin\\libITKImageFeature-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKImageIntensity,
        "bin\\libITKImageIntensity-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKLabelMap,
        "bin\\libITKLabelMap-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKMetaIO,
        "bin\\libITKMetaIO-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKNrrdIO,
        "bin\\libITKNrrdIO-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKRegistrationMethodsv4,
        "bin\\libITKRegistrationMethodsv4-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKSpatialObjects,
        "bin\\libITKSpatialObjects-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTestKernel,
        "bin\\libITKTestKernel-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKTransform,
        "bin\\libITKTransform-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libITKniftiio,
        "bin\\libITKniftiio-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmCommon,
        "bin\\libitkgdcmCommon-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDICT,
        "bin\\libitkgdcmDICT-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmDSED,
        "bin\\libitkgdcmDSED-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libitkgdcmIOD,
        "bin\\libitkgdcmIOD-5.3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
